### ISSUE TITLE
Partitioner: Wrong evaluation of "undefined" Maximum size of a disk (swap)

### ISSUE THREAD

**Issue by kobliha** [openSUSE/agama#1065]
Let's start with the default TW partitioning

1. Swap partition is 1 - 2 GB
2. Click edit
3. Keep "Range"
4. Change Minimum to 16 GB (not needed) and delete the Maximum of 2 GB
5. Click [Accept]
6. Now the swap partition is Min 16 - Max 2 GB

It's probably taking the default when nothing is set, but then it can easily contain a nonsense range.

I've also tried to undef the Minimum size, but Agama is complaining that Minimum must be set.

**Comment by lslezak** [comment]
Fixed in #1142
