### ISSUE TITLE
Add keyboard support for auto-suggested usernames

### ISSUE THREAD

**Issue by dgdavid** [openSUSE/agama#1070]
The list of suggested usernames introduced on #1022 lacks of keyboard support. A [know issue](https://github.com/openSUSE/agama/pull/1022#discussion_r1495704161) that is going to be addressed when time permits.

Initially we agreed on not opening an specific issue for it and refer to #112 instead.

However, I have though that could be useful to left here some useful articles/docs that might help to implement it. See comments below.

**Comment by dgdavid** [comment]
Articles that might help:

* https://whereisthemouse.com/create-a-list-component-with-keyboard-navigation-in-react
* https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Client-side_JavaScript_frameworks/React_accessibility

**Comment by balsa-asanovic** [comment]
Present 😄 

Yeah, I'll be taking this one as we talked about it already in the PR regarding the username auto suggest
