### ISSUE TITLE
Product descriptions are not translated

### ISSUE THREAD

**Issue by imobachgs** [openSUSE/agama#1235]
The product selection always displays the product descriptions in English, although the `agama-products-opensuse` contains translations for many languages.

## How to reproduce it

1. Change the installer language.
2. Navigate to the product selector.
3. The descriptions are in English.

**Comment by lslezak** [comment]
The [translations are present](https://github.com/openSUSE/agama/blob/1bc6b95ce4b5130cb04d553926668eaa4642531a/products.d/tumbleweed.yaml#L13-L55) in the product file.

**Comment by bittin** [comment]
found them missing in the interface with the agama-live.x86_64-8.0.0-openSUSE-Build1.1.iso iso running in gnome-boxes

**Comment by bittin** [comment]
same problem with: agama-live.x86_64-8.0.0-openSUSE-Build1.7.iso

**Comment by imobachgs** [comment]
Thanks for checking. We have not worked on a fix yet but we will update this issue once it is fixed.

**Comment by bittin** [comment]
> Thanks for checking. We have not worked on a fix yet but we will update this issue once it is fixed.

alright thx for the update @imobachgs

**Comment by bittin** [comment]
Still not fixed: https://imgur.com/a/4IgWrN0 and some other pages is missing translations too

**Comment by imobachgs** [comment]
I had a closer look at those issues, and they are actually different problems. Regarding the products not being translated, it should be fixed once https://github.com/openSUSE/agama/pull/1282 is finished, reviewed and merged.

I still have to find out why the pattern descriptions are not translated, given that they come from Libzypp.

**Comment by imobachgs** [comment]
#1375 should fix this (and other) localization problems.

**Comment by imobachgs** [comment]
The fix has been merged. There is still some unwanted flickering, but it will be fixed when we reorganize the routes again.

Thanks!
