### ISSUE TITLE
Software errors: No visible change telling that errors are "clickable"

### ISSUE THREAD

**Issue by kobliha** [openSUSE/agama#1262]
![Software errors - no visible change](https://github.com/openSUSE/agama/assets/463995/04602401-b103-4262-8e76-579e59c070c4)

While every clickable element in the summary page changes at least the color telling that you can get more details by clicking on it, software errors don't change anything. It's a minor thing, but it's inconsistent with the rest of the UI.

The screenshot contains the same snippet twice. Just to show the difference.

**Comment by dgdavid** [comment]
Obsoleted by #1202. Thanks anyway :wink:
