### ISSUE TITLE
Just one swap is allowed :(

### ISSUE THREAD

**Issue by kobliha** [openSUSE/agama#1275]
![Agama - just one swap](https://github.com/openSUSE/agama/assets/463995/84db6b2b-b4b0-4f98-a50f-c4bdd36b3a4c)

Agama does not allow me to create more swap partitions. But why? Is that a feature that I can't have more with different priorities on different disks? I can understand that it tells me that there already is a swap requested, but that should be just _la oferta_ to redefine the first entry, but I believe I should be able to add more if I wish so. It is not a unique entry like /home for instance.

**Comment by ancorgs** [comment]
Yes. Agama doesn't have yet any equivalent to the YaST Expert Partitioner to allow all kind of crazy setups.

What is available so far is what used to be called "Guided Setup" at YaST (but now it allows further customization). And I don't think that guided setup should try to address that kind of advanced scenarios.

**Comment by kobliha** [comment]
OK, understood, then let's close it :)
