### ISSUE TITLE
No VFAT / EFI System FS offered

### ISSUE THREAD

**Issue by kobliha** [openSUSE/agama#1276]
![boot-efi-no-vfat-efisystem](https://github.com/openSUSE/agama/assets/463995/fdfed757-9958-4e9f-8b20-5543c6b0bd87)

![boot-efi-ext4](https://github.com/openSUSE/agama/assets/463995/3093a71d-ebec-42ea-905c-571beaaf7887)

There is no VFAT or EFI System FS offered. Yes, we may say it's a guided proposal, but this is quite a normal thing to decide. Let's say I want to make sure that the one I have on my disk is reused OR I want to really create a new one. Fedora creates new one BTW.

**Comment by kobliha** [comment]
Update: FAT has been already added

**Comment by imobachgs** [comment]
Let's consider it good enough.
