### ISSUE TITLE
Failed LVM proposal

### ISSUE THREAD

**Issue by imobachgs** [openSUSE/agama#1336]
Reported by @jreidinger:

> I created LVM with 2 disks with existing partition. I set partition as shrinkable and it shrink it quite lot..so I reduce size of /home in a hope to get less space for shrinking and result is that I get proposal not possible. Logs from failed attempt attached

**Comment by imobachgs** [comment]
[agama-installation-logs.zip](https://github.com/user-attachments/files/15832142/agama-installation-logs.zip)

**Comment by joseivanlopez** [comment]
According logs, the requested sizes are:

~~~
/             5 GiB
/home  24 GiB
swap     1-2 GiB
~~~

And the selected candidate devices:

~~~
/dev/vda  10 GiB
/dev/vdc  20 GiB
~~~

And the error says: 

~~~
2024-06-13 21:46:47 <1> agama(2703) [Ruby] y2storage/min_guided_proposal.rb(rescue in try_proposal):40 Failed to make a minimal proposal
2024-06-13 21:46:47 <1> agama(2703) [Ruby] y2storage/min_guided_proposal.rb(rescue in try_proposal):41 Error: The volume group system is not big enough
~~~

I think this error is expected. The requestes LVs requires 30 GiB, but that is imposible if both disks sum exactly 30 GiB. There is no space for boot partition, metadata, etc.

**Comment by joseivanlopez** [comment]
Closing because working as expected.
