### ISSUE TITLE
Fail to change the location to a disk that should be formatted

### ISSUE THREAD

**Issue by imobachgs** [openSUSE/agama#1339]
Reported by @jreidinger:

> when I try to set storage volume location to disk that should be formatted, then I get this

![storage_crash](https://github.com/openSUSE/agama/assets/15836/2d06d9aa-626f-4d29-b171-5aebb14c5c51)

**Comment by imobachgs** [comment]
@ancorgs was able to reproduce the problem and he will attach additional information.

**Comment by ancorgs** [comment]
Attaching logs. The failure is in the YaST side. The GuidedProposal exploted somehow.

[agama-logs.Q3Cf26.zip](https://github.com/user-attachments/files/15835939/agama-logs.Q3Cf26.zip)

**Comment by ancorgs** [comment]
Fixed by https://github.com/yast/yast-storage-ng/pull/1385
