### ISSUE TITLE
The first user suggested name is ... undefined

### ISSUE THREAD

**Issue by kobliha** [openSUSE/agama#1364]
![Suggested username - undefined](https://github.com/openSUSE/agama/assets/463995/9d9edeb6-ed96-405d-8665-2a3bd2648fc6)

It's not mandatory to define a real user name, but even then Agama proposes a username (login). Sadly, it's "undefined" :) Which is not wrong per-se as it's at least gender-neutral.

How to reproduce?

1. Surf to the User -> First user
2. Define a user now
3. Click into the Full Name field
4. Don't enter anything
5. Click into the Username field
6. You are offered to add the "undefined" user

Looks like Agama is storing undefined as the user on leaving the field even when nothing is really entered.

**Comment by kobliha** [comment]
![User Full Name is required](https://github.com/openSUSE/agama/assets/463995/68fdf41b-f56e-4277-87db-4c146d346015)

Additionally to that, the Full name is actually required although it's not marked that way. Behaves the same when creating new or editing a user.

**Comment by imobachgs** [comment]
A funny one, indeed. About the required fields, it is in our todo list. We decided to not mark any field with the asterisk but we are not there yet :-/

**Comment by dgdavid** [comment]
Fixed in #1374
