### ISSUE TITLE
Installing software: the "infinite" progress always starts from the beginning with new package

### ISSUE THREAD

**Issue by kobliha** [openSUSE/agama#1373]
![Software installation progress](https://github.com/openSUSE/agama/assets/463995/1b383e2f-5873-4212-87aa-8b8e5ea8ac38)

When Agama is installing software, there is an infinite progress - a rotating busy indicator. This indicator is always reset with a new package. Ideally it should just keep rotating till it's finished with software.

I know it's a minor thing, but it's quite a strange behavior :D And I feel it's rather a bug.

**Comment by imobachgs** [comment]
It looks weird, indeed. Most probably, we will need to change the approach a little bit and stop using that rotating icon because it gets reset when we change the associated description. Using a general progress indicator would do the trick.

**Comment by imobachgs** [comment]
#1388 introduces some changes so that's not a problem anymore. However, we have now a different problem:

[moving-progress.webm](https://github.com/openSUSE/agama/assets/15836/fee7d5ba-3171-4ee4-a64b-eba9d6ca69ef)

**Comment by imobachgs** [comment]
#1395 addresses this problem. Let's consider this bug as fixed.
