### ISSUE TITLE
Crash when playing with storage settings

### ISSUE THREAD

**Issue by ancorgs** [openSUSE/agama#1396]
I will provide more sensible information. But for now, let me attach the logs.

[agama-logs.VPk8RG.zip](https://github.com/user-attachments/files/15992428/agama-logs.VPk8RG.zip)

**Comment by ancorgs** [comment]
More logs from a similar crash. This time I can see something that seems to point to the CompoundActions:

```
Jun 26 23:39:13 agama agamactl[6322]: c:0046 p:---- s:0251 e:000250 CFUNC  :sentence
Jun 26 23:39:13 agama agamactl[6322]: c:0045 p:---- s:0248 e:000247 CFUNC  :public_send
Jun 26 23:39:13 agama agamactl[6322]: c:0044 p:0054 s:0243 e:000242 METHOD /usr/share/YaST2/lib/y2storage/storage_class_wrapper.rb:254
Jun 26 23:39:13 agama agamactl[6322]: c:0043 p:0015 s:0230 e:000229 BLOCK  /usr/share/YaST2/lib/y2storage/storage_class_wrapper.rb:198
Jun 26 23:39:13 agama agamactl[6322]: c:0042 p:0005 s:0225 e:000224 METHOD /usr/lib64/ruby/gems/3.3.0/gems/agama-yast-8.devel631/lib/agama/storage/action.rb:44
```

Of course, it could be a red herring.
[agama-logs.eOEibA.zip](https://github.com/user-attachments/files/15996320/agama-logs.eOEibA.zip)

**Comment by joseivanlopez** [comment]
Yes, the fix in https://github.com/openSUSE/agama/pull/1379 was not enough to avoid losing the reference to the needed actiongraph. There is a hot fix in https://github.com/openSUSE/agama/pull/1400, but let's keep this bug open because a better solution is needed. Check the PR for more details.

**Comment by joseivanlopez** [comment]
Fixed by https://github.com/openSUSE/agama/pull/1410
