### ISSUE TITLE
Improve the installation progress screen

### ISSUE THREAD

**Issue by imobachgs** [openSUSE/agama#141]
From #115: *There are two progress bars in Installing screen, it is not clear what represent each one, I guess on top some current process and the second is for the total, but the steps also do not match with the progress of the second one.*

That screen deserves some more love. However, as we have improved the YaST installation progress, we could learn from there.

**Comment by kobliha** [comment]
Santiago Zarate also says to this:

I only could see "x Remaining" but no information on what the installer is doing (i.e, a list/textbox displaying name of packages being installed)...  so if installation gets stuck an abnormal amount of time on a package, I won't know which one

When notifying how many packages are left the installer says XX Remains when it should say XX packages remaining or Remaining XX imo
