### ISSUE TITLE
Watching installation progress causes headache

### ISSUE THREAD

**Issue by lkocman** [openSUSE/agama#1413]
Hello Aagama team

if you watch install progress and the entire progress jumping up and down, based on the package name length, I suppose the box is not wide enough .... Seems like we need more space or shorten strings.

[Screencast from 2024-06-28 16-37-54.webm](https://github.com/openSUSE/agama/assets/510119/a0bf6e8c-58ce-478b-863a-fd5de50d97b3)

**Comment by kobliha** [comment]
![Installing software](https://github.com/openSUSE/agama/assets/463995/2228e8db-c599-46da-b19f-66ed665491d7)

Please try with Agama 9, this looks much better now. Behaves differently for different screen sizes.

**Comment by imobachgs** [comment]
As @kobliha has said, the progress is much better now. Could you, please, give it a try to the latest version?

**Comment by imobachgs** [comment]
I would say this one is fixed. I am closing the issue. Please, reopen if it is still a problem.

Thanks!
