### ISSUE TITLE
Freshly installed Leap 16 has hostname and prompt set to agama

### ISSUE THREAD

**Issue by lkocman** [openSUSE/agama#1414]
Hello team

it seems that hostname is copied from agama live dvd. I'd expect default hostname to be set to localhost.localdomain or something.
[hostname-logs.zip](https://github.com/user-attachments/files/16032306/hostname-logs.zip)

![image](https://github.com/openSUSE/agama/assets/510119/795eb83e-8665-4459-82ae-40a09257a5bc)

**Comment by imobachgs** [comment]
OK, we need to check that behavior. @teclator please, could you have a look?

About Leap 16.0, it looks like you could install it 😄 However, we were having some troubles two days ago. Do we need to do anything to get the Leap 16.0 configuration working? Thanks!

**Comment by teclator** [comment]
I would say that it is not copied to the target system but set by NetworkManager when getting DHCP.

Agama has a one-shot service for setting the hostname when the installation boots, therefore the hostname will be used when requesting an address by DHCP (@lslezak should know more).

See net-dhcp-leases from a fresh installation

$ sudo virsh net-dhcp-leases default
 Expiry Time           MAC address         Protocol   IP address           Hostname   Client ID or DUID
------------------------------------------------------------------------------------------------------------
 2024-07-02 10:25:26   52:54:00:ae:4a:88   ipv4       192.168.100.161/24   agama      01:52:54:00:ae:4a:88

I guess that running hostnamectl at the installed system will show that it is the transient one, BTW we probably should just set the transient hostname when booting.

**Comment by teclator** [comment]
I need to check if using the transient one is fine with the current mDNS / Avahi documentation.

https://github.com/openSUSE/agama/blob/master/doc/avahi.md#using-mdns

**Comment by teclator** [comment]
Fixed by #1432
