### ISSUE TITLE
Icons for individual distros

### ISSUE THREAD

**Issue by lkocman** [openSUSE/agama#1415]
it would be nice to have product/distribution icons in the product selection screen.
I'd like to work on this one.

**Comment by imobachgs** [comment]
Hi Lubos,

Yes, it would be nice to have the logos on the selection screen, and it is great that you want to work on that. In order to help you to move this forward, do you have any plan for the implementation?

Thanks!

**Comment by kobliha** [comment]
![Product selection](https://github.com/openSUSE/agama/assets/463995/0e1f2244-7b99-4b38-928d-fece5deebd23)

The screen, indeed, needs to be a bit more shiny.

**Comment by kobliha** [comment]
Thinking about it, we may add some labels in bold. Let's say next to each block on the right side.

- Leap: **Stable**
- MicroOS: **Atomic** (or Transactional)
- Tumbleweed: **Rolling**

**Comment by dgdavid** [comment]
> ![Product selection](https://private-user-images.githubusercontent.com/463995/345342586-0e1f2244-7b99-4b38-928d-fece5deebd23.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAwMjU1MzIsIm5iZiI6MTcyMDAyNTIzMiwicGF0aCI6Ii80NjM5OTUvMzQ1MzQyNTg2LTBlMWYyMjQ0LTdiOTktNGIzOC05MjhkLWZlY2U1ZGVlYmQyMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwM1QxNjQ3MTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yY2M3ZDIzMDc4MTBiNTY2NTkyYzIzZDBjYjZkNDQ1YjA0OWIwOTQ1ZWVmNjMzYTM5OTZkNDIxNjAyYTY5NGI2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.aKEbxZfr9NaNT-iGGtRJpCBOE-6c7FyHPuxSVIgJBik)
> 
> The screen, indeed, needs to be a bit more shiny.

Sure, it needs more love. But I'd say that, although a bit related, it's a completely different thing than the original issue. Let's keep them split :wink:

**Comment by dgdavid** [comment]
> Hi Lubos,
> 
> Yes, it would be nice to have the logos on the selection screen, 

In fact, looks like it was in our minds from long ago, see https://github.com/openSUSE/agama/issues/200

> and it is great that you want to work on that. In order to help you to move this forward, do you have any plan for the implementation?

Sure, we can help with that. Thanks in advance, @lkocman

**Comment by lkocman** [comment]
My early experiments 

this one is using <Brand 
![image](https://github.com/user-attachments/assets/0d8fdf09-0281-49c9-aebb-4f59c9e1672c)

And would be useful if you'd have larger logos including the product text. Benefit is that people do not try to click the icon and we can continue using radio buttons.



The other one is with <img, using left float, and vertical and horizontal aligh, heigh set to 100% and width to auto
![image](https://github.com/user-attachments/assets/c37dff98-fc0e-47b5-af2d-4749766c89ff)

I like it better, but we'd have to not use radio, and make the entire card clickable, as otherwise it will confuse users as they'll try to click the icon.

**Comment by lkocman** [comment]
I'll supply some wider logos to show the potential on the first example, before fully eleminating that option.

**Comment by lkocman** [comment]
It was quite painful to get this working but I'm quite happy with the result

![image](https://github.com/user-attachments/assets/7bb590da-c683-4770-a877-49effc4fc040)
