### ISSUE TITLE
code-review: Requiring python-package as a data-sources (pulls in python)

### ISSUE THREAD

**Issue by lkocman** [openSUSE/agama#1426]
Problem found by @darix 

you are requiring a python package just as a data source that means it will pull at least the base python package and the whole dep stack under that

**Comment by lkocman** [comment]
Findings from @imobachgs 

about python-langtable-data, it is supposed to be just a data package. It only depends on:
```
rpmlib(CompressedFileNames) <= 3.0.4-1
rpmlib(FileDigests) <= 4.6.0-1
rpmlib(PayloadFilesHavePrefix) <= 4.0-1
rpmlib(PayloadIsZstd) <= 5.4.18-1
```

**Comment by imobachgs** [comment]
Perhaps I am missing something, but `python-langtable-data` does not require any Python package (AFAIK):

```
rpm -qi python-langtable-data --requires --recommends
[..]
Distribution: openSUSE Tumbleweed
rpmlib(CompressedFileNames) <= 3.0.4-1
rpmlib(FileDigests) <= 4.6.0-1
rpmlib(PayloadFilesHavePrefix) <= 4.0-1
rpmlib(PayloadIsZstd) <= 5.4.18-1
```

Actually, we split the package to not depend on Python. But I might be missing something.

**Comment by imobachgs** [comment]
I do not think there is anything else to do here, so I am closing the issue. Thanks!
