### ISSUE TITLE
Product selection ideas / improvements

### ISSUE THREAD

**Issue by dgdavid** [openSUSE/agama#1434]
![Product selection](https://github.com/openSUSE/agama/assets/463995/0e1f2244-7b99-4b38-928d-fece5deebd23)

The screen, indeed, needs to be a bit more shiny.

> Thinking about it, we may add some labels in bold. Let's say next to each block on the right side.
> 
> * Leap: **Stable**
> * MicroOS: **Atomic** (or Transactional)
> * Tumbleweed: **Rolling**

_Originally posted by @kobliha in https://github.com/openSUSE/agama/issues/1415#issuecomment-2205399821_

**Comment by bittin** [comment]
![bild](https://github.com/openSUSE/agama/assets/43197/16097139-8b1a-4c17-ba92-cbb0d6785596)

When you try to switch language and keyboard layout on the products page, using the cog wheel it sometimes get stuck with an unlimited spinner, when i try in gnome-boxes with todays iso: https://download.opensuse.org/repositories/systemsmanagement:/Agama:/Devel/images/iso/agama-installer-openSUSE.x86_64-9.0.0-openSUSE.iso

**Comment by bittin** [comment]
> ![bild](https://private-user-images.githubusercontent.com/43197/346195154-16097139-8b1a-4c17-ba92-cbb0d6785596.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAzOTc0NTMsIm5iZiI6MTcyMDM5NzE1MywicGF0aCI6Ii80MzE5Ny8zNDYxOTUxNTQtMTYwOTcxMzktOGIxYS00YzE3LWJhOTItY2JiMGQ2Nzg1NTk2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA4VDAwMDU1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMzNDUyZjdhNjAxNGNhZGQ3NWI4NzI4OWQ5YWMyM2NkNWU1OWU0ZGExZDAwNWFmNTc3OTZhODA5NWNkOTNmN2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kyPpSKZvwuzBeo0PuMkGzw6LKCju4h1WLNabwdSVttU)
> 
> When you try to switch language and keyboard layout on the products page, using the cog wheel it sometimes get stuck with an unlimited spinner, when i try in gnome-boxes with todays iso: https://download.opensuse.org/repositories/systemsmanagement:/Agama:/Devel/images/iso/agama-installer-openSUSE.x86_64-9.0.0-openSUSE.iso

This is now fixed :)

**Comment by dgdavid** [comment]
Let's considered this issue solved by https://github.com/openSUSE/agama/pull/1550, which made the product selection screen more appealing and accessible.
