### ISSUE TITLE
Consider gnome-initial-setup or similar to perform some of the first-boot experience

### ISSUE THREAD

**Issue by lkocman** [openSUSE/agama#157]
Hello team,

I've had some discussion regarding our spin of one of our Distribution for employees and gnome-initial-setup is always mentioned for any sort of post-install tweaks.

I think we should perhaps consider utilizing it in the installation process as well https://github.com/endlessm/gnome-initial-setup/blob/master/HACKING

**Comment by kobliha** [comment]
IMO this is only good for (local?) UI and only for GNOME. I'd rather see something based on the same tech as the Installer itself (and the 1:1 Sys Mgmt). That means Cockpit.
