### ISSUE TITLE
Agama runs on tty7, probably should be tty2

### ISSUE THREAD

**Issue by lkocman** [openSUSE/agama#1582]
Hello team,

I noticed that we run agama web-ui on tty7 and probably should be running on tty2 .
openQA console switch functions expect gui to be on tty2 on newer systems, agama runs on tty7.

As of now I workaround it by hardcoding tty7 for installation in the test suite. https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/20126

**Comment by imobachgs** [comment]
Fixed by #1592.
