### ISSUE TITLE
Translations missing 14th September 2024 build

### ISSUE THREAD

**Issue by bittin** [openSUSE/agama#1604]
Hey!

Had some time today to test Agama again (to install Leap 16 Alpha, and Tumbleweed) with this iso: https://download.opensuse.org/repositories/systemsmanagement:/Agama:/Devel/images/iso/agama-installer.x86_64-openSUSE.iso

and noticed a lot of tranlations was missing: https://imgur.com/a/qDMtXx9 even if the project is fully translated on Weblate: https://l10n.opensuse.org/projects/agama/-/sv/ 

(did send an email too)

other then that everything worked

**Comment by imobachgs** [comment]
Hi!

The problem is that we are not considering TypeScript files in the scripts to build the `.pot` file (and we have moved quite some files to TypeScript recently).

Thanks for noticing!

**Comment by bittin** [comment]
> Hi!
> 
> The problem is that we are not considering TypeScript files in the scripts to build the `.pot` file (and we have moved quite some files to TypeScript recently).
> 
> Thanks for noticing!


ah alright i see, well then you and me have something to do before the stable release

**Comment by imobachgs** [comment]
The translations are included again in https://github.com/openSUSE/agama/pull/1611.

Thanks!

**Comment by bittin** [comment]
@imobachgs thx for fixing, will test some more when i feel less sick

**Comment by imobachgs** [comment]
Thank you! Take care!

**Comment by bittin** [comment]
@imobachgs testing now with todays 23th Septembers iso: https://download.opensuse.org/repositories/systemsmanagement:/Agama:/Devel/images/iso/agama-installer.x86_64-openSUSE.iso , more Swedish now atleast, but its not fully complete yet but maybe there is some strings thats not on Weblate yet

**Comment by ancorgs** [comment]
It would be good to have some examples of missing translations, to check the reason(s)... which may be various.

**Comment by bittin** [comment]
> It would be good to have some examples of missing translations, to check the reason(s)... which may be various.

Posted some in  #1629 @ancorgs
