### ISSUE TITLE
Enumerations represented as integers are poorly introspectable on D-Bus

### ISSUE THREAD

**Issue by mvidner** [openSUSE/agama#212]
We have some enumerations that are represented by integers internally

Examples:

- [DInstaller::Status::Base](https://github.com/yast/d-installer/blob/99e23fa289883cf34049545189fdea591230aaba/service/lib/dinstaller/status_manager.rb#L77)
- proposed [Phase and Status](https://gist.github.com/joseivanlopez/ea852cd7e0362244264287510712c0e0#d-bus-iface-orgopensusedinstallerinstallationphase1)

If we use them in the D-Bus interface, it leads to obscuring the meaning of the API which is a pity because in most other respect D-Bus is very introspectable and learnable. This is most visible in the NetworkManager API (TODO: example). The D-Bus specification does not address this problem.

I propose to

1. design a D-Bus interface to make enums introspectable (BTW not via .Introspect)
2. maybe base this on a standard Ruby gem... perhaps [typesafe_enum](https://www.rubydoc.info/gems/typesafe_enum)
3. once 1+2  is stabilized, move it to ruby-dbus and perhaps even the D-Bus specification

### One possibility for introspectable enums:

An API using an enumeration has an annotation, applicable to properties and (in/out) arguments.

name: org.opensuse.Enum
value: object path implementing org.opensuse.Enum1

```xml
<interface name="org.opensuse.DInstaller.Manager1">
  <property name="Status" type="u" access="read">
    <annotation
        name="org.opensuse.Enum"
        value="/org/opensuse/DInstaller/Manager/Status1"
        >
    </annotation>
  </property>
...
</interface>
```

The enumeration values are represented by _objects_ so that they are conveniently visible in d-feet

(Another possibility: a single object for the whole enumeration. returning an array of structs?)

```
/my/tree/FooStatus implements org.opensuse.Enum1
```

but so far I don't see any methods/properties, it is just a parent to EnumValue1

```
/my/tree/FooStatus/200_Success implements org.opensuse.EnumValue1
/my/tree/FooStatus/400_UserError
/my/tree/FooStatus/500_ServerError
org.opensuse.EnumValue1: read-only constant properties:
 Name: ServerError (s)
 Value: 500 (always Int32, regardless of the actual integer type used for the enum)
 Description (s) The input was valid but the operation failed; should retry.
/my/tree/EshopOrderState
/my/tree/EshopOrderState/0_Created
/my/tree/EshopOrderState/1_Paid
/my/tree/EshopOrderState/2_Packaged
/my/tree/EshopOrderState/3_Shipped
```

**Comment by mvidner** [comment]
Ah, the parent interface would probably have a lookup method:
`org.opensuse.Enum1.Lookup(Int32 value) -> ObjectPath`

**Comment by shundhammer** [comment]
Just a wild idea: On the very low library level, Xlib uses the concept of `XInternAtom()` which basically converts a lengthy string into an integer; but that's an integer of very limited life time, just for the length of the current program run. That means that there are no ambiguities for any predefined integers like numeric enum values; it is always simple to add another one, even in the middle of existing ones, not just at the end.

Basic sequence:

```C++
XAtom foo = XInternAtom( "/org/opensuse/yast/our/lengthy/name" );
doSomething( foo, 42 );
doSomeMore( foo, 84 );
...
```

**Comment by mvidner** [comment]
@shundhammer ruby's `String#to_sym` is aliased as `String#intern`, I guess the heritage is clear

**Comment by ancorgs** [comment]
Now that we have switched from D-Bus to HTTP as main communication protocol, I closing this. I know D-Bus is still used internally at some parts, but this is likely not worth any investment.

Feel free to reopen if you disagree.
