### ISSUE TITLE
Consider iOS like entering of (wifi) password (last entered letter is always shown)

### ISSUE THREAD

**Issue by lkocman** [openSUSE/agama#242]
Hello team,

seems like users would like to see what key did just hit and simply don't hope for the best.
https://youtu.be/HejPzBYSExk?t=1523 

I personally have to admit that seeing the letter that I just typed makes me more confident and reduces amount of typos and reduces frustration while typing complex passwords and various devices with various keyboards that we nowadays use.

Unfortunatelly screenshots in iOS remove passwords / stars / dots entirely so here is my artistic take on it :-)
Typing a password "Password" would would look like this from user perspective 
(just imagine it's refreshing).

Password: P
Password: *a
Password: **s
Password: ***s
Password: ****w
Password: *****o
Password: ******r
Password: *******d

**Comment by dgdavid** [comment]
I guess @lkocman means something like https://github.com/iluha5/react-mobile-style-password-input#readme

See borrowed animation from them

![fading-letters-password](https://raw.githubusercontent.com/iluha5/react-mobile-style-password-input/master/react-mobile-like-password-input.gif)

**Comment by imobachgs** [comment]
A comment from #297: *Just a thought, though, is that if someone is actually spying on a person's computer, say, through vnc or what not, that peeper could actually see the entire password as it is typed in. With two fields, then at least the passwords are never shown and the person has to confirm the first password by entering it again.*

**Comment by balsa-asanovic** [comment]
@dgdavid @imobachgs is there still interest in making these changes?

I'd be interested in working on this.

**Comment by imobachgs** [comment]
Hi @balsa-asanovic,

Sure, no problem. However, I would prefer to use the typical "eye" icon instead of showing the last character because it is the pattern I have seen in KDE and GNOME. Any opinion?

Regards,
Imo
