### ISSUE TITLE
Missing validation for data from D-Bus

### ISSUE THREAD

**Issue by joseivanlopez** [openSUSE/agama#302]
The D-Bus API provided by D-Installer uses variant type for some values. For example, when calling to calculate a new storage proposal:

~~~
$ busctl call \
    org.opensuse.DInstaller.Storage \
    /org/opensuse/DInstaller/Storage/Proposal1 \
    org.opensuse.DInstaller.Storage.Proposal1 \
    Calculate \
    a{sv} 1 CandidateDevices as 1 /dev/vdc
~~~ 

There is no validation from backend size about the types sent, so it could fail if it receives an unexpected value:

~~~
$ busctl call \
    org.opensuse.DInstaller.Storage \
    /org/opensuse/DInstaller/Storage/Proposal1 \
    org.opensuse.DInstaller.Storage.Proposal1 \
    Calculate \
    a{sv} 1 CandidateDevices au 1 1000
~~~
 
The backend should verify the data received from D-Bus.

**Comment by ancorgs** [comment]
Now that we have switched from D-Bus to HTTP as main communication protocol, I closing this. I know D-Bus is still used internally at some parts, but this is likely not worth any investment.

Feel free to reopen if you disagree.
