### ISSUE TITLE
Remote installation: Design some better login screen

### ISSUE THREAD

**Issue by kobliha** [openSUSE/agama#364]
D-Installer login screen is just a Cockpit@Tumbleweed login screen not mentioning anything about the Installer itself. It also shows localhost.localdomain while I'm actually connected to some real IP/hostname. 

This is about https://$IP:9090/cockpit/@localhost/d-installer/index.html

It would be great to have a login screen which assures you that this is what you are looking for.

**Comment by imobachgs** [comment]
The login screen has been replaced with our own. Sure there are a few things to improve (especially error handling), but at least it is not the cockpit one anymore.

**Comment by ancorgs** [comment]
There is no Cockpit anymore at Agama and now we have our own login screen (which certainly mentions Agama).
