### ISSUE TITLE
The browser in the live ISO may stop sending queries to D-BUS

### ISSUE THREAD

**Issue by ancorgs** [openSUSE/agama#378]
This only happens when I run the D-Installer Live ISO on real bare-metal hardware (my old laptop). I have not being able to reproduce it in a virtual machine.

Way to reproduce:

 - Boot the ISO until the browser is open
 - Switch to tty1
 - Wait for five minutes
 - Return to tty7
 - Try to perform any action in the web UI that implies interaction with the D-Bus service

Things stop working. The expected queries are never sent from the browser to the D-Bus interface.

Fun enough, with the system in that state I'm able to login from a remote browser and operate normally.

**Comment by imobachgs** [comment]
I was able to reproduce the problem in bare-metal (not tried in a VM, though) and it looks like Cockpit's session times out. You can see a "Connection has timed out" message in the browser's console.

Actually, if you press ctrl+r, you see Cockpit's login screen. I must say that the login screen does not work for me, but I do not know if it might be a consequence of using `cockpit-desktop` to launch the browser. Launching a new firefox works just fine.

**Comment by imobachgs** [comment]
This problem should not happen with the new HTTP/JSON-based architecture.
