### ISSUE TITLE
Fix D-Bus versioning

### ISSUE THREAD

**Issue by joseivanlopez** [openSUSE/agama#408]
D-Bus versioning is wrong, see [D-Bus guidelines](https://dbus.freedesktop.org/doc/dbus-api-design.html#api-versioning). The version number should be added to the service name and to the first word of the object path and iface name. For example:

~~~
org.opensuse.DInstaller.Storage1

/DInstaller/Storage1
  .DInstaller.Storage1
  .DInstaller1.ServiceStatus
  .DInstaller1.Progress
  .DInstaller1.Validation
/DInstaller/Storage1/Proposal
  .DInstaller.Storage1.Proposal
~~~

Generic ifaces like `DInstaller.ServiceStatus1` should be renamed as `DInstaller1.ServiceStatus` because they are associated to the main sevice DInstaller1, although other services (e.g., `DInstaller.Storage1`) can also implement them.

**Comment by mvidner** [comment]
Well, versioning `Progress` and `Validation` together, like this:
```
/DInstaller/Storage1
  .DInstaller1.Progress
  .DInstaller1.Validation
```

implies that when you change the `Validation` API for any reason, you have to fix `Progress` clients too. Is that really what we want?

**Comment by imobachgs** [comment]
We have already adopted this proposal but we forgot to close this issue.
