### ISSUE TITLE
Isolate D-Bus interfaces

### ISSUE THREAD

**Issue by joseivanlopez** [openSUSE/agama#433]
The interface properties and methods are defined by the D-Bus object. If a D-Bus object implements quite some ifaces, then it has to provide all the methods for each intereface, which implies to have a D-Bus object with a lot of possibly unrelated logic. Moreover, we need to pay attention to property/method name collition, specially when importing interfaces from a module:

~~~rb
module MyIface
  def size
    # ...
   end

  def self.included(base)
    base.class_eval do
      dbus_interface "MyIface" do
        dbus_reader :size, "u"
      end
    end
  end
end

class MyObject < DBus::Object
  include MyIface

  dbus_interface "OtherIface" do
    dbus_reader :size, "u"
  end

  def size # name collition with MyIface#size
    # ...
  end
end
~~~

We could use safer method names by prefixing them, for example `dbus_reader :myiface_size, "u", dbus_name: "Size"`, but that implies to use a prefix for all kind of methods we provide in the mixin, even for auxiliary methods.

A better solution would be to have some kind of composition or similar approach for aisolating the interface logic and definition. An idea could be to do something similar to what a service does when exporting D-Bus objects. For example, interfaces are defined in its own class, and then the D-Bus object add them:

~~~rb
class MyObject < DBus::Object
  def initialize
    my_iface1 = DBus::Interface.new
    my_iface2 = DBus::Interface.new

    add_interfaces my_iface1, my_iface2
  end
end
~~~

We could workaround it by implementing some kind of `Interface` and `Object` wrappers around `DBus::Object` in D-Installer, but maybe *ruby-dbus* could also be adapted to offer a new way of defining interfaces. 

In the future, we could also need to dynamically remove interfaces: `remove_interface my_iface1`.

**Comment by ancorgs** [comment]
This becomes less irrelevant now that we are giving up on D-Bus. So closing. Feel free to reopen if you disagree.
