### ISSUE TITLE
Serial line should indicate how to connect to Web UI

### ISSUE THREAD

**Issue by kobliha** [openSUSE/agama#450]
Bug https://bugzilla.suse.com/show_bug.cgi?id=1207877 shows that a customer booted the install media, but did not see anything installer-specific at the serial line (this is a server). IMO there should be a message telling them how to connect to the Web UI remotely (or on the "VGA").

Update: Info is seen _after logging in_ (which is too late)

**Comment by lslezak** [comment]
Fixed in #1311 , the same information is displayed also in the serial console (notice the `ttyS0` terminal :wink: ):

![agama_serial_messages](https://github.com/openSUSE/agama/assets/907998/c2dcdc6e-bb85-4f76-9b2d-5d8653736c76)

**Comment by kobliha** [comment]
Thanks :)
