### ISSUE TITLE
Cockpit port not allowed due to Firewall restrictions

### ISSUE THREAD

**Issue by kobliha** [openSUSE/agama#454]
Bug https://bugzilla.suse.com/show_bug.cgi?id=1207877#c14 additionally mentions that they can access _port_ _9090_ because it's unknown to the firewall (or just internal restrictions). As this is an installation, there is no reason to run another http server on the system, so maybe having _80/443_ as the default or at least configurable option would really help.

**Comment by lslezak** [comment]
Using standard 80/443 would be probably the best approach in this scenario. 

BTW we still have registered port 4984 for WebYaST, we could possibly reuse that if needed is some situations...

https://www.iana.org/assignments/service-names-port-numbers/service-names-port-numbers.xhtml?search=webyast

**Comment by imobachgs** [comment]
Now that we plan [to replace Cockpit](https://github.com/openSUSE/agama/discussions/1000) this might be something to consider.

**Comment by imobachgs** [comment]
We are using standard ports already. So I would expect this to not be a problem anymore.
