### ISSUE TITLE
Proxy setup missing

### ISSUE THREAD

**Issue by kobliha** [openSUSE/agama#456]
In some environments, e.g., https://bugzilla.suse.com/show_bug.cgi?id=1207877#c8 it's needed to access the internet via proxy. This is currently possible only through workarounds, but it's a must-have for production ENV.

**Comment by kobliha** [comment]
HOWTO from @lslezak 

A possible workaround could be to define the proxy settings explicitly in the systemd unit file.

Open the d-installer.service file

  # vim /usr/lib/systemd/system/d-installer.service

Into the "[Service]" section define the PROXY environment variable pointing to *your* proxy. Something like:

  [Service]
  Environment="HTTP_PROXY=http://proxy.example.com:3128/"
  Environment="HTTPS_PROXY=http://proxy.example.com:3128/"

Then reload the systemd and restart the D-Installer service:

  # systemctl daemon-reload
  # systemctl restart d-installer

Then reload the page in the browser.

**Comment by imobachgs** [comment]
Referenced in https://bugzilla.suse.com/show_bug.cgi?id=1212677.

**Comment by imobachgs** [comment]
Already implemented in #696 and #711.
