### ISSUE TITLE
The network configuration generated by dracut (nm-initrd-generator) is not copied to the target system

### ISSUE THREAD

**Issue by teclator** [openSUSE/agama#516]
After the installation we are copying the **/etc/NetworkManager/system-connections/*** files to the target system but the configuration created by the **nm-initrd-generator** is lost as it is in /var/run. 

It could be a problem in case it is an static configuration and maybe we should force a save of the network before booting.

**Comment by mchf** [comment]
https://github.com/openSUSE/agama/pull/997
