### ISSUE TITLE
Create an easy-to-understand development tutorial

### ISSUE THREAD

**Issue by dgdavid** [openSUSE/agama#570]
Probably it's too early to start thinking on it, but...

Lately I have been thinking that, apart from the documentation, we could have a tutorial that is relatively simple to follow by people interested on contributing to the project. In other words, something similar to the YaST journalctl tutorial https://ancorgs.github.io/yast-journalctl-tutorial/

The idea would be to provide a big picture of all parts involved for adding a feature to the Agama project. I mean, the Ruby and/or Rust part (aka the backend), the D-Bus (aka the messenger?), the cockpit project (the glue?), and the React and friends part (aka the frontend).

As a matter of fact, the tutorial shouldn't be too much tied to the tech stack because... you know... everything changes constantly. Rather, it should be just "breadcrumbs" to guide readers to understand the project architecture to have a clear understanding.

As an idea, I was intending to propose using the [UPower D-Bus API](https://upower.freedesktop.org/docs/ref-dbus.html) to endow Agama the ability to know if the system is running [on battery](https://upower.freedesktop.org/docs/UPower.html#UPower:OnBattery) or not and to show a warning before starting the installation. Or even preventing it if the battery level is below a certain threshold. But it lacks the backend :man_shrugging:

**Comment by dgdavid** [comment]
> The idea would be to provide a big picture of all parts involved for adding a feature to the Agama project. I mean, the Ruby and/or Rust part (aka the backend), the D-Bus (aka the messenger?), the cockpit project (the glue?), and the React and friends part (aka the frontend).

@imobachgs, if you don't mind, please check if I left something without mention. Or even better, feel free to re-phrase me and write a more accurate list. Thanks.

**Comment by dgdavid** [comment]
> we could have a tutorial that is relatively simple to follow by people interested on contributing to the project. [...] something similar to [...] https://ancorgs.github.io/yast-journalctl-tutorial/

@ancorgs :roll_eyes: :roll_eyes: :roll_eyes:

**Comment by joseivanlopez** [comment]
I like the idea. Not sure about the backend part, because one of the advantages of the Agama architecture is to be language-agnostic thanks to D-Bus. I would separate backend and frontend tutorials:

* Given a D-Bus API, how to use it from the Web UI
* Given a D-Bus API, how to use it from the command line

And for the backend:
* How to create a D-Bus service (probably focusing in Rust only)

**Comment by dgdavid** [comment]
Months later, I think there is a lot things to do before this can be addressed as it deserves. 

So, let's keep it closed until things are more stabilized and we have time to work on it.
