### ISSUE TITLE
Questions client only reads the first question

### ISSUE THREAD

**Issue by joseivanlopez** [openSUSE/agama#582]
When there are more than one question, *questions.js* only reads the first question.

The bug is here https://github.com/openSUSE/agama/blob/device-selector-ui/web/src/client/questions.js#L135.

**Comment by lalitkumawat1m** [comment]
Hey @joseivanlopez, could you please describe the issue in detail?

**Comment by joseivanlopez** [comment]
This issue is kind of blocked now because we are introducing some changes to the D-Bus API, see https://github.com/openSUSE/agama/pull/637. Probably we will need to adapt the `Questions` cockpit client after merging #637, fixing this issue as part of the adaptation.

I would suggest you to focus on another issue. For example, you might be interested on:

* https://github.com/openSUSE/agama/issues/552
* https://github.com/openSUSE/agama/issues/468

The following ones require some previous discussion, but we are open to suggestions:

* https://github.com/openSUSE/agama/issues/242
* https://github.com/openSUSE/agama/issues/141
* https://github.com/openSUSE/agama/issues/112
