### ISSUE TITLE
Fetch the content for `About` dialog

### ISSUE THREAD

**Issue by dgdavid** [openSUSE/agama#621]
Right now, the content of the [`About`](https://github.com/openSUSE/agama/blob/master/web/src/components/core/About.jsx) dialog is _hard-coded_ in the component itself. But would be nice to _fetch_ the content from somewhere in the filesystem, which would allow customizing it depending on the system/product (including to not show the About link/dialog if the file does not exist or it is empty... or display the _default_ content).

As discussed _offline_, most probably we're going to use [`cockpit.file`](https://cockpit-project.org/guide/latest/cockpit-file.html) over [`fetch`](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API)

**Comment by balsa-asanovic** [comment]
Is there still interest in this?

I could work on it.

**Comment by balsa-asanovic** [comment]
Ah, sorry, didn't notice it was already assigned to @imobachgs 

I'll look for something else 😄

**Comment by imobachgs** [comment]
Hi @balsa-asanovic,

No, please, you can take this one. I am busy with other stuff. Anyway, we might need to define which file we will use. @dgdavid any preference?

**Comment by lslezak** [comment]
We already have the same problem with the [product descriptions](https://github.com/openSUSE/agama/blob/4f83fb462fbb4e78aec9836d92e2f42f0219a874/service/etc/agama.yaml#L9-L12), they are not translated as well.

My idea is to write some script which uses an YAML parser and extracts the texts to a POT file. And have a reverse script which reads the translations from the PO files and writes them next to the original texts with `description-<lang>` key (e.g. `description-de`, `description-es`, ...). The code would then read the translated text or fall back to the original untranslated (`description`) if a translation is not found.

(Note: it's a bit tricky as we need to keep the YAML structure including the comments, but it seems that the JS [yaml](https://www.npmjs.com/package/yaml) library can [do this](https://eemeli.org/yaml/#parser).)

**Comment by balsa-asanovic** [comment]
> We already have the same problem with the [product descriptions](https://github.com/openSUSE/agama/blob/4f83fb462fbb4e78aec9836d92e2f42f0219a874/service/etc/agama.yaml#L9-L12), they are not translated as well.
> 
> My idea is to write some script which uses an YAML parser and extracts the texts to a POT file. And have a reverse script which reads the translations from the PO files and writes them next to the original texts with `description-<lang>` key (e.g. `description-de`, `description-es`, ...). The code would then read the translated text or fall back to the original untranslated (`description`) if a translation is not found.
> 
> (Note: it's a bit tricky as we need to keep the YAML structure including the comments, but it seems that the JS [yaml](https://www.npmjs.com/package/yaml) library can [do this](https://eemeli.org/yaml/#parser).)

Seems like an interesting endeavour, I'll look into it and try to make those scripts.

**Comment by lslezak** [comment]
JFYI I have implemented support for translating the `description` key. The translatable texts from YAML files are collected and saved to the [products.pot](https://github.com/openSUSE/agama-weblate/blob/master/products/products.pot) file.

After translating in Weblate (that does not work currently) the translations are merged back to the YAML into the [`translations` key](https://github.com/openSUSE/agama/blob/master/products.d/tumbleweed.yaml#L12).

We can easily add a new `about` key in the YAML config and translate it the same way.

**Comment by lslezak** [comment]
BTW see related pull requests https://github.com/openSUSE/agama/pull/851, https://github.com/openSUSE/agama/pull/853 and https://github.com/openSUSE/agama/pull/855

**Comment by balsa-asanovic** [comment]
Hey, sorry for not getting around to doing this 😢 

> BTW see related pull requests https://github.com/openSUSE/agama/pull/851, https://github.com/openSUSE/agama/pull/853 and https://github.com/openSUSE/agama/pull/855

I'll check out these PR's to see what have you done.

Is there anything more regarding this issue I could help you with?

**Comment by imobachgs** [comment]
Hi @balsa-asanovic,

No problem! @lslezak commented on this issue because he implemented a mechanism to have the product descriptions (which now live in [products.d](https://github.com/openSUSE/agama/tree/master/products.d)) translated. Of course, do not hesitate to ask any questions you might have.

Actually, we have not paid attention to this issue because it is not urgent. We now display a translated text (the translation comes directly from the component) and plan to keep that the same by now.

However, if you already have done some work on this issue, we can continue. In any other case, I could suggest a different topic to work on if you want.

Thanks in advance!

**Comment by balsa-asanovic** [comment]
Hey @imobachgs 

> However, if you already have done some work on this issue, we can continue. In any other case, I could suggest a different topic to work on if you want.

No, I still haven't done anything related to this, so feel free to suggest other topics, I am willing to help.

**Comment by imobachgs** [comment]
We are not implementing this feature by now. We could re-open it if we change our mind. Thanks!
