### ISSUE TITLE
Downloading the logs does not work

### ISSUE THREAD

**Issue by imobachgs** [openSUSE/agama#697]
It looks like the feature to download the logs does not work. In the console you get a `missing "path" option for fsread channel` message when clicking the link.

**Comment by dgdavid** [comment]
While trying to find out what is wrong there, I realized that _awaiting_ for the logs' path fixes the problem and they are downloaded as expected.

```diff
diff --git a/web/src/client/manager.js b/web/src/client/manager.js
index 87b14a7f..ee847521 100644
--- a/web/src/client/manager.js
+++ b/web/src/client/manager.js
@@ -86,7 +86,7 @@ class ManagerBaseClient {
    */
   async fetchLogs() {
     const proxy = await this.client.proxy(MANAGER_IFACE);
-    const path = proxy.CollectLogs("root");
+    const path = await proxy.CollectLogs("root");
     const file = cockpit.file(path, { binary: true });
     return file.read();
   }
```

**Comment by dgdavid** [comment]
I'm not able to find where is the breaking change that does not allow a path as promise anymore. The _protocol-error_ is raised by a CockpitChannel at https://github.com/mvollmer/cockpit/blob/5aa80a427dcf289608b217db16f98bdd0d06dbe9/src/bridge/cockpitfsread.c#L207C7-L207C27 but apparently were no changes in the latest 5 years. 

There were no changes in our side neither apart from the rename from D-installer to Agama.

Anyway, I'll send the fix and move on.
