### ISSUE TITLE
`PasswordAndConfirmationInput` leftover

### ISSUE THREAD

**Issue by dgdavid** [openSUSE/agama#760]
While reviewing #750, I realized that `PasswordAndConfirmationInput` has a leftover _split_ prop.

Initially it was there to allow choosing between a vertical or horizontal layout but actually it was never used. In any case, we should go for a _direction_ prop instead if we really need something similar the future.

For now, I'd just drop both, the prop and the wrapping div.

https://github.com/openSUSE/agama/blob/2d4284241bbd3b0960df06f2a442f9d22dc6e74a/web/src/components/core/PasswordAndConfirmationInput.jsx#L29-L57

Just a good-first-issue or something to commit in #750, #759, or later.

**Comment by balsa-asanovic** [comment]
> Just a good-first-issue or something to commit in https://github.com/openSUSE/agama/pull/750, https://github.com/openSUSE/agama/pull/759, or later.

Sure, I can tackle this through #750 as well.

**Comment by avdhendra** [comment]
can i work on this issue

**Comment by dgdavid** [comment]
> can i work on this issue

Thanks a lot, but @balsa-asanovic already picked it and I don't know if he already committed in his local branch. Maybe you guys can coordinate if it isn't done yet.

In any case, I'll try to look for more good-first-issues in the incoming days :)

BTW, welcome to the Agama project 👋

**Comment by balsa-asanovic** [comment]
> can i work on this issue

Hey @avdhendra,

I was already working on this component as a part of #750 when the issue was raised, so I took care of it since it wasn't a big change.

Sorry for taking a 'good first issue' from you :sweat_smile: 

Be sure to follow the issues, I am sure another one will pop up.
