### ISSUE TITLE
Improve file and directory names in `agama logs store`

### ISSUE THREAD

**Issue by imobachgs** [openSUSE/agama#774]
Agama CLI recently got a `logs store` command (see #757). It is a nice starting point, but I would like to do some suggestions:

* Do not use names with spaces and dashes (eg., `journalctl --dmesg.out.log`). I would rather prefer something like `dmesg.log` and `dmesg.err.log`.
* Use a top-level directory. By now, if you extract the content, you get all the content extracted to the directory where you are located. Having everything under an `agama-logs` directory would be better...
* ... and that brings me to the following topic. In `save_y2logs` we add a random suffix to the name. I would like the same behavior to be implemented in `logs store`. Actually, the name of the top-level directory could be the same (e.g, `agama-logs-Oh4MtC`).

**Comment by mchf** [comment]
regarding the second ... logs are collected in a temporary directory which already has such a random suffix, so at least this one is easily achievable by not packing directory content (<tempdir>/*> but directory itself (<tempdir>), I'll add it to the "to improve list" I'm working on.

**Comment by mchf** [comment]
@imobachgs I assume we can close this one, right?

**Comment by mchf** [comment]
Implemented in PR#780
