### ISSUE TITLE
Create a helper for logging errors to the console

### ISSUE THREAD

**Issue by dgdavid** [openSUSE/agama#842]
Little by little, we're adding some useful `console.error` to the code for helping the developer to know if something is wrong and how to solve it.

But we should avoid to output these messages in the production build since they are neither, visible nor useful for the user. So, saving some bits from the build would be nice.

To do so, I'd add a helper method into [utils](https://github.com/openSUSE/agama/blob/master/web/src/utils.js) that receives a message and outputs it to the `console.error` only if `process.env.NODE_ENV` is not `production`.

See more details at https://github.com/openSUSE/agama/pull/816#discussion_r1377345662

For tests, look at https://github.com/openSUSE/agama/blob/master/web/src/components/layout/Icon.test.jsx to get some inspiration.

**Comment by imobachgs** [comment]
I do not know if I like this change. When dealing with bugs, it would be great to have the messages from the console, including the `console.err` calls. I know that we are not including this information in our logs yet, but I would not close the door.

**Comment by dgdavid** [comment]
> I know that we are not including this information in our logs yet, but I would not close the door.

Good point.

Moreover, I was writing a comment that made me realize that maybe is not a good idea because the size we will save is negligible and we can catch some overlooked errors in production too.

Just for the record, I was commenting that

> * `logError` might or might not be a good name. Could it create confusion and make the developer think that message will be written in the Agama logs file? // cc @imobachgs 
> * Not all `console.error` might be wrapped. For example, https://github.com/openSUSE/agama/blob/72cbbbd6b3c85e06ea97652060528b2754ba878e/web/src/context/software.jsx#L43
