### ISSUE TITLE
Pattern descriptions are not translated

### ISSUE THREAD

**Issue by lslezak** [openSUSE/agama#859]
## Problem

After switching the display language to Spanish the pattern descriptions are still displayed in English.

![pattern-selector-spanish](https://github.com/openSUSE/agama/assets/907998/b57b9b6e-5169-4d83-ae38-6d5c558b3be1)

## Details

Libzypp loads the translations for the current language when the repository is refreshed. The translations are located in the `repo/*-susedata.<lang>.xml.gz` files. See examples in https://download.opensuse.org/tumbleweed/repo/oss/repodata/.

Libzypp loads only a single file with the current language, the rest is ignored to save time and the network bandwidth.

## Proposed Solution

Because the language might be switched after loading the initial repository we need to refresh the repositories again with the new language.

See related https://github.com/openSUSE/agama/pull/875.

*Note: For really using the new translations we probably also need to reload the libzypp pool from scratch. That means we need to restore also the selected products/patterns/packages back.*

**Comment by ShatilKhan** [comment]
I can take this one @lslezak 
Please assign me

**Comment by dgdavid** [comment]
Hi @ShatilKhan,

Sorry, but I think this one is rather difficult and should be fixed by the team. So, unless @lslezak has another view, I'd encourage you to pick another one if you want contribute.

Thanks anyway for your willing to help here.

**Comment by lslezak** [comment]
I agree, this is not a trivial task, this needs a libzypp and yast-pkg-bindings expert. I'd recommend to start with something easier...

**Comment by lslezak** [comment]
Implemented in PR #991, closing.
