### ISSUE TITLE
Extract issues link from sidebar

### ISSUE THREAD

**Issue by joseivanlopez** [openSUSE/agama#872]
We have agreed to use the sidebar for actions related to the installer itself (e.g., diagnosis tools, display lang, etc). Everything related to the target system to install should not be placed in the siderbar.

The only thing related to the target system still present in the sidebar is the issues link. The issues should be globally accessible from another place (footer, header, ...).

**Comment by dgdavid** [comment]
You were faster than me :)  I was redacting the issue for exactly the same, after a morning meeting with @imobachgs for reviewing pending stuff in the Agama UI and generating some detailed issues.

What is more, I was thinking on @balsa-asanovic for this one, as I got the impression he wanted to continue contributing. But, of course, it's just a suggestion.

In any case, I'll add my view as a comment here as soon as I finish it.

**Comment by balsa-asanovic** [comment]
> What is more, I was thinking on @balsa-asanovic for this one, as I got the impression he wanted to continue contributing. But, of course, it's just a suggestion.

Agreed. 👍 

Also, if there are some other issues you think I could help with, feel free to suggest those as well.
