### ISSUE TITLE
The installation progress screen cannot be translated

### ISSUE THREAD

**Issue by bittin** [openSUSE/agama#906]
would be great if the installing packages text could be localized to installerar paket

**Comment by imobachgs** [comment]
Hi @bittin,

Thanks for your feedback. If you do not mind, I will keep this issue for the translation of the installation progress screen and I will keep a new one for Leap 16.

**Comment by bittin** [comment]
> Hi @bittin,
> 
> Thanks for your feedback. If you do not mind, I will keep this issue for the translation of the installation progress screen and open a new one for Leap 16.
> 
> The problem with the installation progress is that the strings are [not marked for translation](https://github.com/opensuse/agama/blob/6ebe3ba3f9640a39f5650345c7648e4770b68f29/service/lib/agama/manager.rb#L117-L121).

nah its all fine :)

**Comment by ancorgs** [comment]
> The problem with the installation progress is that the strings are not marked for translation

That's true. But the problem goes a little bit further. The Ruby part of the Agama service is currently not translatable. So a bit a infrastructure work is needed there.

**Comment by bittin** [comment]
@imobachgs @ancorgs alright feel free to ping me when/if this changes so i can update the Swedish translation, just updated it with this weeks new strings

**Comment by imobachgs** [comment]
It is already possible to translate the progress and, actually, you already did :wink: So I am closing this bug report.

Thanks!

**Comment by bittin** [comment]
@imobachgs still some other strings that can't be translated however but i guess things are still under development
feel free to ping me on bittin(a)opensuse.org when more things can be translated, and i will translate things to Swedish when i can :)
