### ISSUE TITLE
Leap 16 cannot be installed

### ISSUE THREAD

**Issue by imobachgs** [openSUSE/agama#907]
It is not possible to install Leap 16 because of some dependencies problems. It is not clear whether it is a problem in [Agama's product definition](https://github.com/openSUSE/agama/blob/master/products.d/leap16.yaml) or a real Leap 16 problem.

Originally reported in #906.

**Comment by ancorgs** [comment]
I would invoke @lkocman here.

Lubos, is this ALP-based Leap something that is really being developed and should be installable?

If so, please check what needs to be adapted at https://github.com/openSUSE/agama/blob/master/products.d/leap16.yaml (maybe the definition of patterns?)

If no, please tell us to (temporarily) remove that product from Agama selection

**Comment by lslezak** [comment]
The solver reports these dependency problems:
```
Encountered problems! Here are the solutions:

Problem 1:
====================================
nothing provides 'libboost_thread.so.1.81.0()(64bit)' needed by the to be installed snapper-0.10.4-9.3.x86_64
------------------------------------
do not install pattern:alp_base-5.0-5.2.x86_64
------------------------------------
ignore some dependencies of U__s_(672)snapper-0.10.4-9.3.x86_64(https-download.opensuse.org-cfb92eb9)
------------------------------------
Problem 2:
====================================
nothing provides 'libboost_thread.so.1.81.0()(64bit)' needed by the to be installed snapper-0.10.4-9.3.x86_64
------------------------------------
do not install pattern:alp_defaults-5.0-5.2.x86_64
------------------------------------
ignore some dependencies of U__s_(672)snapper-0.10.4-9.3.x86_64(https-download.opensuse.org-cfb92eb9)
------------------------------------
Problem 3:
====================================
nothing provides 'libboost_thread.so.1.81.0()(64bit)' needed by the to be installed snapper-0.10.4-9.3.x86_64
------------------------------------
do not install pattern:alp_base_zypper-5.0-5.2.x86_64
------------------------------------
ignore some dependencies of U__s_(672)snapper-0.10.4-9.3.x86_64(https-download.opensuse.org-cfb92eb9)
------------------------------------
Problem 4:
====================================
nothing provides 'libboost_thread.so.1.81.0()(64bit)' needed by the to be installed snapper-0.10.4-9.3.x86_64
------------------------------------
do not install pattern:alp-container_runtime-5.0-5.2.x86_64
------------------------------------
ignore some dependencies of U__s_(672)snapper-0.10.4-9.3.x86_64(https-download.opensuse.org-cfb92eb9)
```

It seems there is some problem with the boost library, the latest version available in the Leap 16.0 is libboost_thread1_80_0-1.80.0-4.8.x86_64.rpm built on 4.1.2023. (see the [repository](https://download.opensuse.org/repositories/openSUSE:/Leap:/16.0/images/repo/Leap-16.0-x86_64-Media1/x86_64/))

**Comment by lkocman** [comment]
I'll make SR to drop it from configs.

**Comment by bittin** [comment]
@lkocman and me @bittin talked about this in todays openSUSE Release meeting

**Comment by bittin** [comment]
This is now temporarily removed, atleast from the new daily images

**Comment by imobachgs** [comment]
Thanks! I am closing the issue as the decision, by now, is to not offer Leap 16.
