### ISSUE TITLE
The storage menu is out of place

### ISSUE THREAD

**Issue by imobachgs** [openSUSE/agama#949]
It looks like after merging #925, the storage menu is out of place. This one is a blocker for releasing version 7. @dgdavid, please, could you have a look?

![Captura desde 2023-12-21 22-57-52](https://github.com/openSUSE/agama/assets/15836/32226fb9-dc49-45ab-b8c8-eab6744490fc)

**Comment by dgdavid** [comment]
> @dgdavid, please, could you have a look?

Sure, I'll do. Most probably, this happens because of the `type.name.endsWith` thingy I was talking with you. Weird because I did a `npm run build` to check "ProposalPageMenu" name was not obfuscated... and it worked. I guess I did something wrong when testing it.

Anyway, let's have a look.

**Comment by dgdavid** [comment]
> Most probably, this happens because of the `type.name.endsWith` thingy 

https://github.com/openSUSE/agama/blob/a1c7f330f8149f85d1e57932b3514bec912844bb/web/src/components/core/Page.jsx#L179

**Comment by dgdavid** [comment]
> Weird because I did a `npm run build` to check "ProposalPageMenu" name was not obfuscated

Reviewing my bash history.... I forgot about `NODE_ENV=production` thingy. Please, excuse me :pray: 

(Temporary?) Fix is already available at #950, please check it.
