### ISSUE TITLE
wrong encoding of Swedish letters + gnome-terminal not starting

### ISSUE THREAD

**Issue by bittin** [openSUSE/agama#987]
Hey!

i have been testing Agama with openSUSE Tumbleweed during the first month of this year 
and the encoding of letters is wrong in the Wayland GNOME Environment for example when it creates the Downloads folder its called HÃ¤mtningar instead of Downloads

and also it has problems with launching gnome-terminal # Error constructing proxy for org.gnome.Terminal:/org/gnome/Terminal/Factory0: Fel vid anrop av StartServiceByName fÃ¶r org.gnome.Terminal: TidsgrÃ¤nsen uppnÃ¥ddes
tried to start it with english language but got the exact same problem: # Error constructing proxy for org.gnome.Terminal:/org/gnome/Terminal/Factory0: Error calling StartServiceByName for org.gnome.Terminal: Timeout was reached 

xfce4-terminal works however

**Comment by imobachgs** [comment]
This problem does not happen on a system installed using YaST. That's why we think it is a bug.

**Comment by mvidner** [comment]
This kind of garbled text means the text is encoded in UTF-8 (as expected) but the terminal interprets it as ISO-8859-x.

_Hypothesis_: we write the locale identifier as `sv_SE` (which is fine on the web) but that one uses ISO-8859-1. We should write `sv_SE.UTF-8` instead.

```console
$ locale -av
...
locale: sv_SE           directory: /usr/lib/locale/sv_SE
-------------------------------------------------------------------------------
    title | Swedish locale for Sweden
 language | Swedish
territory | Sweden
  codeset | ISO-8859-1

locale: sv_SE.utf8      directory: /usr/lib/locale/sv_SE.utf8
-------------------------------------------------------------------------------
    title | Swedish locale for Sweden
 language | Swedish
territory | Sweden
  codeset | UTF-8
...
```

**Comment by imobachgs** [comment]
Hi all,

Thanks @mvidner, you are right! I confirmed that we are not including the encoding. We could 1) force to use UTF-8 always (which is almost a one-liner) or 2) take the encoding into account (which looks more correct to me). I am working on the solution 2).

**Comment by imobachgs** [comment]
Once #992 has been merged, I will consider the issue solved. I have installed the system in Swedish and it seems to work:

![Captura desde 2024-01-16 13-38-32](https://github.com/openSUSE/agama/assets/15836/f6de4f45-ea73-44b3-8377-0a95ec9a24c5)

Thanks for the report!

**Comment by bittin** [comment]
> Once #992 has been merged, I will consider the issue solved. I have installed the system in Swedish and it seems to work:
> 
> ![Captura desde 2024-01-16 13-38-32](https://private-user-images.githubusercontent.com/15836/297070150-f6de4f45-ea73-44b3-8377-0a95ec9a24c5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU0MTM1MzAsIm5iZiI6MTcwNTQxMzIzMCwicGF0aCI6Ii8xNTgzNi8yOTcwNzAxNTAtZjZkZTRmNDUtZWE3My00NGIzLTgzNzctMGE5NWVjOWEyNGM1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE2VDEzNTM1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZiNTgyMDY0OTVkYmJlZDhkMjJhMWI3N2M0ZjZiYWFjNDg5MzRkZjYzYzgyZDg5Y2NlNDdiMGZhNzNjNmFlMTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5dn6RlwZfAyz1tDFVuaFWcOC9QNrbxAWmByjocoGv3Q)
> 
> Thanks for the report!

was actually my partner that found this bug before me, but glad to see it now being solved in tomorrows daily image
