### ISSUE TITLE
Agama does not work with the new Python-based bridge

### ISSUE THREAD

**Issue by imobachgs** [openSUSE/agama#998]
Agama does not seem to work with the new Python-based bridge (enabled [in request 1138363](https://build.opensuse.org/request/show/1138363), even updating `cockpit.js.`

* Considers `UILocale` as a read-only D-Bus property.
* I cannot access `/org/freedesktop/NetworkManager/AccessPoint`.
* Setting `/agama/index.html` as the default module does not work.

As a workaround, we are using the old bridge in `agama-live`.

**Comment by bittin** [comment]
#989 is now fixed

**Comment by imobachgs** [comment]
According to https://github.com/openSUSE/agama/discussions/1000 we plan to replace Cockpit so I will close this issue. We can reopen if we change our mind.

**Comment by bittin** [comment]
alright

**Comment by SecT0uch** [comment]
Seems like I have both issue using the last build (25/01):
I'm unable to change the timezone and Networks loads indefinitely.

**Comment by bittin** [comment]
@SecT0uch have you tried if its still a problem with the daily Staging isos too?

https://download.opensuse.org/repositories/systemsmanagement:/Agama:/Staging/images/iso/agama-live.x86_64-openSUSE.iso

**Comment by SecT0uch** [comment]
Thanks! Daily staging works :)
